### ISSUE TITLE
This tool is not able to Parse a Valid JSON File that is parsed by any online json viewer tool perfectly.

### ISSUE THREAD

**Issue by ertanuj96** [denandz/sourcemapper#11]
Hello There,

I was trying to use this tool to extract the original source code from the SourceMap File, but when I loaded this tool and give this a sourcemap url, its giving  the error while it should parse this json, as the json is perfect.
Here is the snapshot, kindly have a look and fix this issue as soon as possible.
![image](https://github.com/denandz/sourcemapper/assets/27552153/e7adbe06-e799-40fe-8b74-511b37b1d672)

The Source Map URL that is not loading properly in this tool is :
https://www.subway.com/dist/RemoteOrder/js/components/customizer/index.js.map

Thanks & Regards
Tanuj Sharma

**Comment by denandz** [comment]
You're getting this error because the server is returning HTTP 404 not found. The sourcemap isn't there.
