### ISSUE TITLE
I dont know what to do about this error?

### ISSUE THREAD

**Issue by Th3Mag1c1an** [denandz/sourcemapper#12]
2023/09/04 13:06:34 [+] Retrieving Sourcemap from https://hub.docker.com/public/js/core.c68661edc8.js.map.
2023/09/04 13:06:35 [+] Read 2359 bytes, parsing JSON.
2023/09/04 13:06:35 [!] Error parsing JSON - confirm https://hub.docker.com/public/js/core.c68661edc8.js.map a valid JS sourcemap
2023/09/04 13:06:35 invalid character '<' looking for beginning of value

//# sourceMappingURL=https://sourcemaps.d.musta.ch/airbnb/static/packages/web/common/frontend/hyperloop-browser/core.c68661edc8.js.map maybe it is a self closed source map hard to obtain publically

**Comment by llllvvuu** [comment]
This is probably the reason:
https://github.com/denandz/sourcemapper/blob/f23713532d0c5d4a93538b8508890bb43565d7a5/README.md?plain=1#L45

> Note, Dockerhub have since removed this map file so the literal command below will not provide this output any more.

**Comment by Th3Mag1c1an** [comment]
I guess the js file was different than the following command file, or you are saying that in general, I can not get .map files.

**Comment by denandz** [comment]
This error happens when the requested url doesn't return a valid sourcemap file. Verify that it is in fact a sourcemap file with `curl -i <mapurl>`. It should return a json sourcemap blob.

**Comment by Th3Mag1c1an** [comment]
curl -i https://sourcemaps.d.musta.ch/airbnb/static/packages/web/common/frontend/hyperloop-browser/core.c68661edc8.js.map
curl: (7) Failed to connect to sourcemaps.d.musta.ch port 443 after 8911 ms: Connection refused
I guess that this is not something that I could connect to and get this JS code. I was trying to see the airbnb.co.in main page js code but looks like sourcemaps.d.musta.ch doesn't allow any connection.

**Comment by Th3Mag1c1an** [comment]
You cant obtain this type of js code right where the source is closed right ?

**Comment by denandz** [comment]
`curl: (7) Failed to connect to sourcemaps.d.musta.ch port 443 after 8911 ms: Connection refused` This is your problem. You cant reach the web server that is allegedly hosting the sourcemap. 

Closing this issue, since it's not due to a problem with sourcemapper.
