### ISSUE TITLE
Is there any way to compress everything to one file / minifying to one file again?

### ISSUE THREAD

**Issue by 4lve** [denandz/sourcemapper#6]
I want to modify a script then make it one file again basically

**Comment by denandz** [comment]
You'd need to rebuild the source, probably using whatever yarn/node/whatever tooling the original codebase used. If you're trying to tweak front end source code on the fly, I've had some luck in the past by figuring out what code I needed to tweak in the minified source then writing a match/replace rule in an intercepting proxy. You can beautify the minified code which should help with trying to find the location to patch. 

Closing this issue, as source recompilation isn't something that sourcemapper is designed to deal with.
