### ISSUE TITLE
invalid character '/' looking for beginning of value

### ISSUE THREAD

**Issue by mtmfahathdev** [denandz/sourcemapper#9]

**Comment by denandz** [comment]
do you have an example source map that causes the error?

**Comment by UxplnJDK** [comment]
i am also facing the same problem...i also used the example file in read.md section ..its giving invalid character looking for beginning of value

**Comment by DOLORESH4Z3** [comment]
same problem here

**Comment by DOLORESH4Z3** [comment]
![Problem](https://github.com/denandz/sourcemapper/assets/71711914/11c30da0-a186-4484-a1f8-fef316ab1cf9)

**Comment by anasbousselham** [comment]
Same error.

**Comment by denandz** [comment]
This is the error you get when you don't provide a path to a valid source-map file. Please make sure you are specifying a path to a valid `.map` file

**Comment by denandz** [comment]
Better error messaging when the sourcemap is likely invalid has been added in commit 02d6d3ececea70d9fb3462fb3547a666ad3dd65f
